2018-12-01 06:02:17 ERROR Internal Server Error: /api/topic/
Traceback (most recent call last):
  File "/home/tongthanaphon/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/tongthanaphon/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/tongthanaphon/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tongthanaphon/anaconda3/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tongthanaphon/anaconda3/lib/python3.6/site-packages/django/views/generic/base.py", line 63, in view
    if hasattr(self, 'get') and not hasattr(self, 'head'):
  File "/home/tongthanaphon/anaconda3/lib/python3.6/site-packages/rest_framework/request.py", line 412, in __getattr__
    return getattr(self._request, attr)
  File "/home/tongthanaphon/anaconda3/lib/python3.6/site-packages/rest_framework/request.py", line 412, in __getattr__
    return getattr(self._request, attr)
  File "/home/tongthanaphon/anaconda3/lib/python3.6/site-packages/rest_framework/request.py", line 412, in __getattr__
    return getattr(self._request, attr)
  [Previous line repeated 306 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
2018-12-01 06:02:17 ERROR "GET /api/topic/ HTTP/1.1" 500 1257415
2018-12-01 06:02:19 ERROR Internal Server Error: /api/topic/
Traceback (most recent call last):
  File "/home/tongthanaphon/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/tongthanaphon/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/tongthanaphon/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tongthanaphon/anaconda3/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tongthanaphon/anaconda3/lib/python3.6/site-packages/django/views/generic/base.py", line 63, in view
    if hasattr(self, 'get') and not hasattr(self, 'head'):
  File "/home/tongthanaphon/anaconda3/lib/python3.6/site-packages/rest_framework/request.py", line 412, in __getattr__
    return getattr(self._request, attr)
  File "/home/tongthanaphon/anaconda3/lib/python3.6/site-packages/rest_framework/request.py", line 412, in __getattr__
    return getattr(self._request, attr)
  File "/home/tongthanaphon/anaconda3/lib/python3.6/site-packages/rest_framework/request.py", line 412, in __getattr__
    return getattr(self._request, attr)
  [Previous line repeated 306 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
2018-12-01 06:02:19 ERROR "GET /api/topic/ HTTP/1.1" 500 1257416
2018-12-01 06:02:40 ERROR Internal Server Error: /api/topic/
Traceback (most recent call last):
  File "/home/tongthanaphon/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/tongthanaphon/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/tongthanaphon/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tongthanaphon/anaconda3/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tongthanaphon/anaconda3/lib/python3.6/site-packages/django/views/generic/base.py", line 63, in view
    if hasattr(self, 'get') and not hasattr(self, 'head'):
  File "/home/tongthanaphon/anaconda3/lib/python3.6/site-packages/rest_framework/request.py", line 412, in __getattr__
    return getattr(self._request, attr)
  File "/home/tongthanaphon/anaconda3/lib/python3.6/site-packages/rest_framework/request.py", line 412, in __getattr__
    return getattr(self._request, attr)
  File "/home/tongthanaphon/anaconda3/lib/python3.6/site-packages/rest_framework/request.py", line 412, in __getattr__
    return getattr(self._request, attr)
  [Previous line repeated 306 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
2018-12-01 06:02:40 ERROR "GET /api/topic/ HTTP/1.1" 500 1257415
2018-12-01 06:02:43 ERROR Internal Server Error: /api/topic/
Traceback (most recent call last):
  File "/home/tongthanaphon/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/tongthanaphon/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/tongthanaphon/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tongthanaphon/anaconda3/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tongthanaphon/anaconda3/lib/python3.6/site-packages/django/views/generic/base.py", line 63, in view
    if hasattr(self, 'get') and not hasattr(self, 'head'):
  File "/home/tongthanaphon/anaconda3/lib/python3.6/site-packages/rest_framework/request.py", line 412, in __getattr__
    return getattr(self._request, attr)
  File "/home/tongthanaphon/anaconda3/lib/python3.6/site-packages/rest_framework/request.py", line 412, in __getattr__
    return getattr(self._request, attr)
  File "/home/tongthanaphon/anaconda3/lib/python3.6/site-packages/rest_framework/request.py", line 412, in __getattr__
    return getattr(self._request, attr)
  [Previous line repeated 306 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
2018-12-01 06:02:43 ERROR "GET /api/topic/ HTTP/1.1" 500 1257416
